baseURL = 'https://shinya.click/'
languageCode = 'zh-cn'
title = 'èœç‹—ã®æ—¥å¸¸'
theme = 'tania'

[params]
titleEmoji = "ğŸ˜ƒ"
siteKeyword = "shinya,Shinya,blog,åšå®¢"
siteDesc = "Shinya's Blog,shinya çš„åšå®¢"
siteAuthor = "shinya"

[menu]
header = [
#    { name = "Articles", url = "/articles/", weight = 1 },
    { name = "Tags", url = "/tags/", weight = 2 },
    { name = "Projects", url = "/projects/", weight = 3 },
    { name = "About", url = "/about/", weight = 4 },
]
footer = [
    { name = "RSS", url = "/index.xml" },
]


[markup.highlight]
noClasses = false
lineNos = true

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS", "JSON"]